### ISSUE TITLE
Overflow error when assembling daily/main targetphot

### ISSUE THREAD

**Issue by weaverba137** [moustakas/desi-photometry#20]
I'm trying to assemble the photometry associated with the daily reductions. The command I ran was
```
srun --ntasks 128 $HOME/Documents/Code/git/moustakas/desi-photometry/mpi-photometry --outdir $PSCRATCH/lsdr9-photometry/dailydb --zcatdir $DESI_ROOT_READONLY/spectro/redux/dailydb/zcatalog/v1 --specprod dailydb --targetphot
```
When running on the `main` survey, there was an overflow error:
```
INFO:mpi-photometry:288:targetphot_observed: Working on survey main
INFO:mpi-photometry:78:read_one_zcat: Read 29,889,947/38,637,000 objects from /dvs_ro/cfs/cdirs/desi/spectro/redux/dailydb/zcatalog/v1/ztile-main-dark-cumulative.fits
INFO:mpi-photometry:78:read_one_zcat: Read 22,041,011/29,328,500 objects from /dvs_ro/cfs/cdirs/desi/spectro/redux/dailydb/zcatalog/v1/ztile-main-bright-cumulative.fits
INFO:mpi-photometry:78:read_one_zcat: Read 5,394,885/13,543,500 objects from /dvs_ro/cfs/cdirs/desi/spectro/redux/dailydb/zcatalog/v1/ztile-main-backup-cumulative.fits
INFO:mpi-photometry:315:targetphot_observed: Distributing 57,325,843 TARGETIDs and 14,086 unique tiles from survey main across 128 ranks
Traceback (most recent call last):
  File "/global/homes/b/bweaver/Documents/Code/git/moustakas/desi-photometry/mpi-photometry", line 958, in <module>
    main()
  File "/global/homes/b/bweaver/Documents/Code/git/moustakas/desi-photometry/mpi-photometry", line 943, in main
    targetphot_observed(args.specprod, args.zcatdir, args.outdir, comm=comm, mp=args.mp)
  File "/global/homes/b/bweaver/Documents/Code/git/moustakas/desi-photometry/mpi-photometry", line 321, in targetphot_observed
    zcat_survey = comm.bcast(zcat_survey, root=0)
  File "mpi4py/MPI/Comm.pyx", line 1569, in mpi4py.MPI.Comm.bcast
  File "mpi4py/MPI/msgpickle.pxi", line 720, in mpi4py.MPI.PyMPI_bcast
  File "mpi4py/MPI/msgpickle.pxi", line 146, in mpi4py.MPI.pickle_dump
  File "mpi4py/MPI/msgbuffer.pxi", line 50, in mpi4py.MPI.downcast
OverflowError: integer 4012809879 does not fit in 'int'
```
After the overflow, `mpi-photometry` just hangs. I had to ^C to exit.
 
I'm guessing the `int` in this case is a C-style 32-bit signed integer, but it's not clear where the number comes from.

**Comment by moustakas** [comment]
I'm running into the same issue with `kibo`. I've already reached out to @sbailey to see if he can help with some MPI magic, e.g., https://github.com/desihub/redrock/pull/311.

**Comment by weaverba137** [comment]
OK, thanx, at least this is a reproducible issue.

**Comment by moustakas** [comment]
@weaverba137 @sbailey, with #21, gathering the targeting photometry for the `dailydb` sample took approximately 75 minutes with 128 tasks on a single interactive node. My invocation is below (or you're welcome to use modified versions of my shell and slurm scripts `/pscratch/sd/i/ioannis/lsdr9/kibo/{lsdr9-kibo.sh,lsdr9-kibo.slurm}`), and you can inspect the results at `/pscratch/sd/i/ioannis/lsdr9-photometry/dailydb`

Note that the resulting `observed-targets` catalogs are 59GB in size and the filenames for the database loading should be self-explanatory (I have not yet updated my README). Briefly, files are now organized by survey and program except for `main-dark` and `main-bright`, which are split into `nside=1` healpixels.

Based on my runs with `kibo`, the `targetphot-potential` catalogs will require a factor of ~7 more disk space and will take up to a factor of 2.5 times longer to generate, depending on how many nodes you use, of course.

The `tractorphot` and `tractorphot-potential` portion of the code is currently running for `kibo` (there are roughly ~50M unique observed targets) and if those finish to completion I will merge #21.

Please let me know if you have any questions and note that whatever tests you're able to do of the generated catalogs would be terrific.

```
salloc -N 1 -C cpu -A desi -t 04:00:00 --qos interactive

source /dvs_ro/common/software/desi/desi_environment.sh main
module swap desiutil/3.4.3
module swap desispec/0.66.0
module swap desitarget/2.8.0
module swap desimodel/0.19.1

time srun --nodes=1 --ntasks=128 $HOME/code/desihub/desi-photometry/mpi-photometry \
  --outdir=$PSCRATCH/lsdr9-photometry/dailydb --zcatdir=$DESI_ROOT_READONLY/spectro/redux/dailydb/zcatalog/v1 \
  --specprod=dailydb --targetphot
```

**Comment by moustakas** [comment]
Heads up that I'm tracking down a few small issues, so I recommend waiting for me to merge #21 before proceeding with your "official" database load, although doing any kind of validation on the `dailydb/observed-catalogs/targetphot-*.fits` catalogs would still be useful.

**Comment by weaverba137** [comment]
I'll try to take a look today, but I'll be busy with meetings for a couple of hours.

**Comment by weaverba137** [comment]
I took a quick look. Everything looks fine so far. If the columns haven't changed, there won't be any issue loading these.

**Comment by moustakas** [comment]
@weaverba137 OK, please try now with `desi-photometry/main`.

In case it's helpful, I've summarized some combinations of nodes and timings which may help you here:
https://github.com/moustakas/desi-photometry/issues/23#issuecomment-2409140582

And I've also put together a template slurm and shell script which you are more than welcome to copy over to you $PSCRATCH and use (although I recommend checking out your own local copy of `desi-photometry`:
```/pscratch/sd/i/ioannis/lsdr9/dailydb```

**Comment by weaverba137** [comment]
@moustakas, thank you, I will test as soon as I can, although I am on vacation most of this week.
